"use client";

import { useEffect } from "react";
import { useLocale } from "next-intl";

// Temporary compatibility dictionary for feature screens while their text is
// progressively moved to namespaced next-intl messages. Exact phrases win;
// the ordered phrase list also handles counters and interpolated values.
export const LEGACY_EN = {
  "التقارير": "Reports",
  "الإعدادات": "Settings",
  "الحجوزات": "Bookings",
  "النظافة": "Housekeeping",
  "حجز جديد": "New booking",
  "حجز مباشر": "Direct booking",
  "غرفة قياسية": "Standard room",
  "شركات": "Corporate",
  "وصول متأخر، سرير زيادة…": "Late arrival, extra bed…",
  "الغرف": "Rooms",
  "وصول اليوم": "Arrivals today",
  "خروج اليوم": "Departures today",
  "تحتاج تنظيف": "Needs cleaning",
  "مشغولة": "Occupied",
  "شاغرة": "Available",
  "معطلة": "Out of service",
  "نظيفة": "Clean",
  "تمت مراجعتها": "Inspected",
  "كل الغرف جاهزة.": "All rooms are ready.",
  "باقي الغرف": "Other rooms",
  "المدير بس": "Managers only",
  "خلصت": "Done",
  "حالة الغرف": "Room status",
  "اضغط على غرفة لعرض تفاصيلها واتخاذ إجراء.": "Select a room to view details and actions.",
  "تحديث": "Refresh",
  "اتصل": "Call",
  "واتساب": "WhatsApp",
  "تسكين": "Check in",
  "تسجيل خروج": "Check out",
  "تم التسكين": "Guest checked in",
  "تمديد الإقامة": "Extend stay",
  "تحقق": "Check availability",
  "تأكيد التمديد": "Confirm extension",
  "الغرفة شاغرة حتى هذا التاريخ.": "The room is available through this date.",
  "نقل إلى غرفة أخرى": "Move to another room",
  "نقل النزيل": "Move guest",
  "النقل يبدأ من": "Move starting on",
  "عرض الغرف المتاحة": "Show available rooms",
  "السبب (اختياري)": "Reason (optional)",
  "انقل هنا": "Move here",
  "إلغاء": "Cancel",
  "تعطيل الغرفة": "Take room out of service",
  "إرجاع الغرفة للخدمة": "Return room to service",
  "من": "From",
  "لحد": "To",
  "السبب": "Reason",
  "تأكيد التعطيل": "Confirm outage",
  "احجز الغرفة دي": "Book this room",
  "جارٍ التحميل…": "Loading…",
  "جارٍ الحساب…": "Calculating…",
  "لا توجد بيانات.": "No data.",
  "آخر ٧ أيام": "Last 7 days",
  "آخر شهر": "Last month",
  "الشهر الحالي": "This month",
  "آخر ٣ شهور": "Last 3 months",
  "مدة محددة": "Custom range",
  "نسبة الإشغال": "Occupancy",
  "إيراد الغرف": "Room revenue",
  "متوسط سعر الليلة": "Average daily rate",
  "إيراد الغرفة المتاحة": "Revenue per available room",
  "حجوزات": "Bookings",
  "ليالي ضيوف": "Guest nights",
  "محصّل": "Collected",
  "متبقي": "Outstanding",
  "للليلة المباعة": "Per sold room-night",
  "مقياس الأداء الحقيقي": "Core performance measure",
  "الإشغال يوم بيوم": "Daily occupancy",
  "رسم بياني للإشغال اليومي": "Daily occupancy chart",
  "الإيراد محسوب بالليلة — الإقامة الممتدة على شهرين تُقسَّم بينهما.": "Revenue is calculated per night, so stays spanning two months are split correctly.",
  "المحصّل حسب طريقة الدفع": "Collected by payment method",
  "لمطابقة الكاش آخر الوردية.": "For end-of-shift cash reconciliation.",
  "الحجوزات جت منين": "Booking sources",
  "فلوس متبقية": "Outstanding balances",
  "سجل الإلغاءات": "Cancellation log",
  "مين ألغى إيه وامتى وليه.": "Who cancelled what, when and why.",
  "كاش": "Cash",
  "إنستاباي": "Instapay",
  "فودافون كاش": "Vodafone Cash",
  "فيزا": "Card",
  "تحويل بنكي": "Bank transfer",
  "مكالمة": "Phone",
  "حضور مباشر": "Walk-in",
  "الموقع": "Website",
  "مواقع حجز": "OTA",
  "توصية": "Referral",
  "أخرى": "Other",
  "لم يحضر": "No-show",
  "ملغي": "Cancelled",
  "ابدأ برقم الهاتف — إذا سبق للنزيل الإقامة ستظهر بياناته تلقائياً.": "Start with the phone number. Returning guests will appear automatically.",
  "رقم الهاتف": "Phone number",
  "بحث": "Search",
  "اسم النزيل": "Guest name",
  "نزيل جديد": "New guest",
  "الدخول": "Check-in",
  "الخروج": "Check-out",
  "تاريخ المغادرة يجب أن يكون بعد الوصول": "Check-out must be after check-in",
  "الغرف الشاغرة": "Available rooms",
  "اضغط على غرفة لاختيارها، وحدد عدد الأفراد بها.": "Select a room and set its occupancy.",
  "لا توجد غرف شاغرة في هذه التواريخ.": "No rooms are available for these dates.",
  "جهة الحجز": "Rate plan",
  "الشركة (اختياري)": "Company (optional)",
  "— بدون —": "— None —",
  "مصدر الحجز": "Booking source",
  "ملاحظات": "Notes",
  "تأكيد الحجز": "Confirm booking",
  "جارٍ التسجيل…": "Saving…",
  "السعر صفر — التركيبة دي لسه مالهاش سعر في الإعدادات.": "This combination has no price in Settings yet.",
  "الحجوزات الحالية": "Current bookings",
  "كل الحجوزات": "All bookings",
  "ابحث بالاسم أو رقم الهاتف أو رقم الحجز": "Search by guest, phone or booking reference",
  "الكل": "All",
  "مؤكد": "Confirmed",
  "مقيم": "Checked in",
  "غادر": "Checked out",
  "إلغاء الحجز": "Cancel booking",
  "عدم حضور": "No-show",
  "مغادرة مبكرة": "Early check-out",
  "المدفوعات": "Payments",
  "إضافة دفعة": "Add payment",
  "استرداد": "Refund",
  "طريقة الدفع": "Payment method",
  "المبلغ": "Amount",
  "تسجيل الدفعة": "Record payment",
  "الإجمالي": "Total",
  "المدفوع": "Paid",
  "الباقي": "Balance",
  "الأسعار": "Rates",
  "الموظفين": "Staff",
  "بيانات الفندق": "Property details",
  "حفظ الأسعار": "Save rates",
  "عدد الأفراد": "Occupancy",
  "أنواع الغرف": "Room types",
  "أقصى عدد": "Maximum occupancy",
  "الاسم": "Name",
  "الاسم بالإنجليزية": "English name",
  "الكود": "Code",
  "إضافة نوع": "Add room type",
  "رقم غرفة جديدة": "New room number",
  "النوع": "Type",
  "إضافة": "Add",
  "إضافة موظف": "Add staff member",
  "المالك": "Owner",
  "مدير": "Manager",
  "استقبال": "Reception",
  "نظافة": "Housekeeping",
  "موقوف": "Suspended",
  "تغيير كلمة المرور": "Change password",
  "إيقاف الحساب": "Suspend account",
  "تفعيل الحساب": "Activate account",
  "حفظ البيانات": "Save details",
  "اسم الفندق": "Hotel name",
  "اسم الفندق بالإنجليزية": "Hotel name in English",
  "رقم الواتساب": "WhatsApp number",
  "رابط الشعار": "Logo URL",
  "اللون الأساسي": "Primary colour",
  "كلمة مرور المدير": "Manager password",
  "جارٍ التنفيذ…": "Working…",
  "رجوع": "Back",
  "إغلاق": "Close",
  "حفظ": "Save",
  "إضافة موظف جديد": "Add staff member",
  "الإيميل": "Email address",
  "اسم المستخدم": "Username",
  "اسم المستخدم (يُستخدم لتسجيل الدخول)": "Username (used to sign in)",
  "3 أحرف إنجليزية أو أرقام على الأقل، دون مسافات. مثال: ahmed أو reception1": "At least 3 English letters or numbers, with no spaces. Example: ahmed or reception1",
  "يسجّل الموظف الدخول باسم المستخدم وكلمة المرور فقط، دون بريد إلكتروني. سلّمه الاثنين بنفسك.": "Staff sign in using only their username and password. Give them both directly.",
  "كلمة المرور": "Password",
  "تأكيد كلمة المرور": "Confirm password",
  "تأكيد كلمة المرور الجديدةة": "Confirm new password",
  "أعد إدخال كلمة المرور": "Enter the same password again",
  "الصلاحية": "Role",
  "حفظ الموظف": "Save staff member",
  "تغيير الأسعار": "Change rates",
  "الدور": "Floor",
  "أحمد محمود": "Ahmed Mahmoud",
  "الإدارة": "Administration",
  "بواسطة": "by",
  "تم فحصها": "Inspected",
  "نوع العملية": "Action type",
  "كل العمليات": "All actions",
  "سجل العمليات": "Activity log",
  "تم تسجيل دفعة": "Payment recorded",
  "تم نقل الغرفة": "Room moved",
  "تم إنشاء الحجز": "Booking created",
  "تم إلغاء الحجز": "Booking cancelled",
  "النظافة والغرف": "Housekeeping and rooms",
  "تم تسكين النزيل": "Guest checked in",
  "تم تسجيل استرداد": "Refund recorded",
  "تم تمديد الإقامة": "Stay extended",
  "تم تقصير الإقامة": "Stay shortened",
  "تم تسجيل عدم حضور": "No-show recorded",
  "تم تحديث البيانات": "Details updated",
  "الحجوزات والإقامة": "Bookings and stays",
  "جارٍ تحميل السجل…": "Loading the log…",
  "تغيرت حالة النظافة": "Housekeeping status changed",
  "بحث في سجل العمليات": "Search the activity log",
  "تم تسجيل خروج النزيل": "Guest checked out",
  "لا توجد عمليات مطابقة.": "No matching actions.",
  "تمت إعادة الغرفة للخدمة": "Room returned to service",
  "السجل للمدير والمالك فقط": "The log is for managers and the owner only",
  "تم تغيير كلمة مرور المدير": "Manager password changed",
  "ابحث بالنزيل أو الموظف أو الحجز أو الغرفة": "Search by guest, staff member, booking or room",
  "كل عمليات الفندق بالترتيب، والموظف الذي نفّذها.": "Every action at the hotel in order, and who carried it out.",
  "سجل العمليات يحتوي على تفاصيل الموظفين والمدفوعات.": "The activity log contains staff and payment details.",
  "خرج": "Departed",
  "ساكن": "In house",
  "اليوم": "Today",
  "ابحث…": "Search…",
  "مدفوع": "Paid",
  "ملاحظة": "Note",
  "استفسار": "Enquiry",
  "الملغية": "Cancelled",
  "الدفعات": "Payments",
  "المنتهية": "Completed",
  "إلغاء غرفة": "Cancel a room",
  "المتبقي كله": "The whole balance",
  "＋ تسجيل دفعة": "＋ Record a payment",
  "يحتاج تدخلاً": "Needs attention",
  "إلغاء الغرفة": "Cancel the room",
  "تأكيد الإلغاء": "Confirm cancellation",
  "بدون سبب محدد": "No reason given",
  "مدفوع بالكامل": "Paid in full",
  "تسجيل عدم حضور": "Record a no-show",
  "تسجيل الاسترداد": "Record the refund",
  "الحالية والقادمة": "Current and upcoming",
  "تأكيد عدم الحضور": "Confirm the no-show",
  "هذا استرداد للنزيل": "This is a refund to the guest",
  "أدخل مبلغاً صحيحاً": "Enter a valid amount",
  "تأكيد إلغاء الغرفة": "Confirm cancelling the room",
  "عربون، باقي الحساب…": "Deposit, balance…",
  "تم تسجيل عدم الحضور": "No-show recorded",
  "لا توجد حجوزات هنا.": "No bookings here.",
  "إلغاء الحجز بالكامل": "Cancel the whole booking",
  "تاريخ الخروج الجديد": "New check-out date",
  "تأكيد المغادرة المبكرة": "Confirm the early check-out",
  "تأكيد بكلمة مرور المدير": "Confirm with the manager password",
  "تم إلغاء الغرفة من الحجز": "The room was removed from the booking",
  "النزيل ألغى، ظروف طارئة…": "Guest cancelled, emergency…",
  "مبلغ يُحتسب عليه (إن وُجد)": "Amount to charge (if any)",
  "لا توجد غرف على هذا الحجز.": "No rooms on this booking.",
  "مغادرة مبكرة (تقصير الإقامة)": "Early check-out (shorten the stay)",
  "تم تقصير الإقامة وتعديل الحساب": "The stay was shortened and the bill adjusted",
  "تم إلغاء الحجز وعادت الغرف متاحة": "The booking was cancelled and the rooms are available again",
  "هذا الحجز مغلق، ولا توجد إجراءات عليه.": "This booking is closed; no actions are available.",
  "ابحث بالاسم أو رقم الهاتف أو رقم الحجز.": "Search by name, phone number or reference.",
  "المغادرة المبكرة تُنقص الحساب، ولذلك تتطلب تأكيداً.": "An early check-out reduces the bill, so it needs confirmation.",
  "باقي غرف الحجز تبقى كما هي، ويُعدّل الحساب تلقائياً.": "The booking's other rooms stay as they are, and the bill adjusts itself.",
  "تعود الغرف للبيع فوراً، فما زال من الممكن بيع هذه الليلة.": "The rooms go back on sale at once, since tonight can still be sold.",
  "تُحذف الليالي التي لن يقيمها من الحساب، وتعود الغرفة للبيع.": "The nights they will not stay come off the bill, and the room goes back on sale.",
  "الإلغاء والتعديل يتطلبان اتصالاً — حتى تعود الغرفة للبيع فوراً.": "Cancelling and amending need a connection, so the room goes back on sale at once.",
  "الدفعات لا تُحذف. يُصحَّح الخطأ باسترداد، حتى يبقى السجل كاملاً.": "Payments are never deleted. A mistake is corrected with a refund, so the record stays complete.",
  "تسجيل الدفعات يتطلب اتصالاً — حتى لا يتعارض الرصيد إذا سُجّل من جهازين.": "Recording payments needs a connection, so the balance cannot disagree if two devices record at once.",
  "النزيل مقيم حالياً. الإلغاء سيُخلي الغرفة فوراً — إذا كان سيغادر مبكراً فاستخدم «مغادرة مبكرة» بدلاً من ذلك.": "The guest is in house. Cancelling empties the room at once — if they are leaving early, use “early check-out” instead.",
  "نزيل سابق.": "Previous guest.",
  "أدخل اسم النزيل": "Enter the guest's name",
  "اختر غرفة واحدة على الأقل": "Choose at least one room",
  "راجع التواريخ": "Check the dates",
  "تم حجز الغرفة منذ لحظات. حدّث الصفحة واختر غرفة أخرى.": "The room was booked moments ago. Refresh and choose another.",
  "السعر صفر — هذه التركيبة ليس لها سعر بعد في الإعدادات.": "The price is zero — this combination has no rate in settings yet.",
  "أفراد": "guests",
  "متاحة": "Available",
  "مباشر": "Walk-in",
  "صيانة": "Maintenance",
  "النزيل": "Guest",
  "الغرفة": "Room",
  "الإقامة": "Stay",
  "المغادرة": "Departure",
  "رقم الحجز": "Reference",
  "نوع الحجز": "Booking type",
  "نظرة اليوم": "Today overview",
  "تكييف معطل": "Air conditioning broken",
  "خارج الخدمة": "Out of service",
  "جارٍ البحث…": "Searching…",
  "تشغيل الفندق": "HOTEL OPERATIONS",
  "مغادرة اليوم": "Departures today",
  "تسجيل الوصول": "Check in",
  "الغرف المشغولة": "Occupied rooms",
  "تم تعطيل الغرفة": "Room taken out of service",
  "دليل حالات الغرف": "Room status legend",
  "تم تسجيل التمديد": "Extension recorded",
  "اضغط لعرض التفاصيل": "Select to see details",
  "جارٍ تسجيل الخروج…": "Checking out…",
  "عادت الغرفة للخدمة": "The room is back in service",
  "جاهزة للنزيل القادم": "Ready for the next guest",
  "لا يوجد وصول مسجّل اليوم.": "No arrivals recorded today.",
  "تم نقل النزيل وتعديل الحساب": "The guest was moved and the bill adjusted",
  "— نوع مختلف، وقد يتغير السعر": "— a different type, so the price may change",
  "تم التسجيل، وسيُرسل فور عودة الاتصال": "Recorded, and it will be sent when the connection returns",
  "اضغط على أي غرفة لعرض التفاصيل والإجراءات.": "Select any room to see its details and actions.",
  "تم تسجيل المغادرة، وأُضيفت الغرفة إلى قائمة النظافة": "Check-out recorded, and the room was added to the cleaning list",
  "التمديد يتطلب اتصالاً — يجب التأكد أن الغرفة شاغرة فعلاً قبل تأكيدها للنزيل.": "Extending needs a connection: the room must be confirmed free before promising it to the guest.",
  "إيراد الإضافات": "Extras revenue",
  "الإضافات المباعة": "Extras sold",
  "ما يبيعه الفندق غير الغرفة.": "What the hotel sells besides the room.",
  "لا توجد ليالٍ مباعة في هذه المدة. كل الأرقام أصفار.": "No nights were sold in this period. Every figure is zero.",
  "سنجل": "Single",
  "دابل": "Double",
  "فطار": "Breakfast",
  "تريبل": "Triple",
  "رباعي": "Quad",
  "خماسي": "Five",
  "سداسي": "Six",
  "الوصف": "Description",
  "الموظف": "Staff member",
  "المواسم": "Seasons",
  "العنوان": "Address",
  "الإضافات": "Extras",
  "صيف ٢٠٢٦": "Summer 2026",
  "تم الحفظ": "Saved",
  "موظف جديد": "New staff member",
  "غرفة بحرية": "Sea view room",
  "حذف الصورة": "Remove the image",
  "جهات الحجز": "Rate plans",
  "أعد إدخاله": "Enter it again",
  "لون الفندق": "Hotel colour",
  "جارٍ الحفظ…": "Saving…",
  "شعار الفندق": "Hotel logo",
  "اختيار صورة": "Choose an image",
  "إنشاء الحساب": "Create the account",
  "＋ إضافة موظف": "＋ Add a staff member",
  "جارٍ الإضافة…": "Adding…",
  "سياسة الإلغاء": "Cancellation policy",
  "تمت إضافة النوع": "Room type added",
  "أدخل رقم الغرفة": "Enter the room number",
  "تم تفعيل الحساب": "Account activated",
  "تم إيقاف الحساب": "Account suspended",
  "كلمة مرور جديدة": "New password",
  "إزالة كلمة المرور": "Remove the password",
  "تمت إضافة الغرفة": "Room added",
  "8 أحرف على الأقل": "At least 8 characters",
  "تم تغيير الصلاحية": "Role changed",
  "4 أرقام على الأقل": "At least 4 digits",
  "تفعيل كلمة المرور": "Turn the password on",
  "الوصف بالإنجليزية": "English description",
  "المحتوى الإنجليزي": "English content",
  "تم حفظ كلمة المرور": "Password saved",
  "معاينة شعار الفندق": "Hotel logo preview",
  "جارٍ الرفع والحفظ…": "Uploading and saving…",
  "نظافة — النظافة فقط": "Housekeeping — cleaning only",
  "كلمة المرور الجديدة": "New password",
  "تأكيد تغيير الأسعار": "Confirm the rate change",
  "كلمة المرور المبدئية": "Initial password",
  "الاسم والكود مطلوبان": "The name and code are required",
  "نعم، أزل كلمة المرور": "Yes, remove the password",
  "تمت إزالة كلمة المرور": "The password was removed",
  "حفظ المحتوى الإنجليزي": "Save the English content",
  "كلمة المرور غير متطابقة": "The passwords do not match",
  "مدير — كل شيء والأسعار": "Manager — everything, including rates",
  "إزالة كلمة مرور التأكيد؟": "Remove the confirmation password?",
  "سياسة الإلغاء بالإنجليزي": "Cancellation policy in English",
  "كلمتا المرور غير متطابقتين": "The two passwords do not match",
  "تم حفظ الترجمات الإنجليزية": "The English translations were saved",
  "استقبال — يحجز ويسكّن ويقبض": "Reception — books, checks in, takes payment",
  "اختر صورة PNG أو JPG أو WebP.": "Choose a PNG, JPG or WebP image.",
  "حجم الصورة يجب ألا يتجاوز 5 ميجا.": "The image must be 5MB or smaller.",
  "أضف نوع غرفة أولاً من تبويب الغرف.": "Add a room type first, from the Rooms tab.",
  "«أقصى عدد» يحدد صفوف مصفوفة الأسعار.": "“Maximum occupancy” sets the rows of the rate grid.",
  "PNG أو JPG أو WebP — بحد أقصى 5 ميجا.": "PNG, JPG or WebP — up to 5MB.",
  "كلمة المرور يجب أن تكون 8 أحرف على الأقل": "The password must be at least 8 characters",
  "تم تغيير كلمة المرور. سلّمه الكلمة الجديدة.": "The password was changed. Give them the new one.",
  "كلمة المرور مفعّلة. هذه الإجراءات تتطلب تأكيداً.": "The password is on. These actions require confirmation.",
  "الخانة الفارغة تعرض الاسم أو الوصف العربي تلقائياً.": "An empty box falls back to the Arabic name or description.",
  "الاسم واسم المستخدم بالإنجليزية مطلوبان، بحد أدنى 3 أحرف": "The name and an English username are required, at least 3 characters",
  "أدخل 8 أحرف على الأقل، ثم سلّم كلمة المرور للموظف بطريقة آمنة.": "Enter at least 8 characters, then hand the password to the staff member securely.",
  "تغيير السعر يؤثر على كل حجز جديد، ولذلك يتطلب كلمة مرور المدير.": "A rate change affects every new booking, so it needs the manager password.",
  "لا توجد كلمة مرور. أي مستخدم لديه صلاحية يمكنه الإلغاء دون تأكيد.": "No password is set. Anyone with permission can cancel without confirming.",
  "بعد الإزالة، لن تطلب إجراءات الإلغاء وعدم الحضور تأكيداً إضافياً.": "Once removed, cancellations and no-shows will not ask for further confirmation.",
  "كل موظف يرى ما يخصه فقط. موظف النظافة لا يرى المبالغ ولا بيانات النزلاء.": "Each staff member sees only their own work. Housekeeping sees no money and no guest details.",
  "كلمة مرور تُطلب قبل الإلغاء وعدم الحضور والمغادرة المبكرة وتغيير الأسعار.": "A password asked for before cancelling, no-shows, early check-out and rate changes.",
  "سعر الليلة للغرفة كاملة. الخانة الفارغة تعني أن هذه التركيبة غير معروضة للبيع.": "The nightly price for the whole room. An empty box means that combination is not for sale.",
};

const REPLACEMENTS = [
  ["، ", ", "],
  ["جنيه", "EGP"], [" ج", " EGP"], ["ليلة", "night"], ["ليالي", "nights"],
  ["غرفة", "room"], ["غرف", "rooms"], ["أفراد", "guests"], ["فرد", "guest"],
  ["حجز", "booking"], ["عملية", "transaction"], ["بواسطة", "by"],
  ["آخر تحديث:", "Last updated:"], ["هذه بيانات محفوظة، وليست لحظية.", "This is saved data, not live data."],
  ["إجراء مستني الإرسال.", "action waiting to be sent."], ["إجراء بانتظار الإرسال.", "action waiting to be sent."],
  ["غرفة تحتاج إجراءً.", "room needs attention."], ["الحساب", "account"],
  ["فلوس متبقية", "Outstanding balances"], ["بالليلة", "per night"],
  ["السعر", "rate"], ["تاريخ", "date"], ["جديد", "new"], ["اليوم", "today"]
];

export function translateLegacyText(value) {
  if (!value || !/[\u0600-\u06FF]/.test(value)) return value;
  const leading = value.match(/^\s*/)?.[0] || "";
  const trailing = value.match(/\s*$/)?.[0] || "";
  const core = value.trim();
  if (LEGACY_EN[core]) return `${leading}${LEGACY_EN[core]}${trailing}`;
  let out = core;
  for (const [ar, en] of REPLACEMENTS) out = out.split(ar).join(en);
  return `${leading}${out}${trailing}`;
}

function translateTree(root) {
  if (!root || typeof NodeFilter === "undefined") return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node;
  while ((node = walker.nextNode())) {
    if (["SCRIPT", "STYLE"].includes(node.parentElement?.tagName)) continue;
    const translated = translateLegacyText(node.nodeValue);
    if (translated !== node.nodeValue) node.nodeValue = translated;
  }
  const elements = root.querySelectorAll?.("[placeholder], [title], [aria-label]") || [];
  for (const el of elements) {
    for (const attr of ["placeholder", "title", "aria-label"]) {
      if (!el.hasAttribute(attr)) continue;
      const current = el.getAttribute(attr);
      const translated = translateLegacyText(current);
      if (translated !== current) el.setAttribute(attr, translated);
    }
  }
}

export default function LegacyTranslator() {
  const locale = useLocale();

  useEffect(() => {
    if (locale !== "en") return;
    translateTree(document.body);
    const observer = new MutationObserver((records) => {
      for (const record of records) {
        if (record.type === "characterData") {
          const translated = translateLegacyText(record.target.nodeValue);
          if (translated !== record.target.nodeValue) record.target.nodeValue = translated;
        } else {
          for (const node of record.addedNodes) {
            if (node.nodeType === Node.TEXT_NODE) {
              const translated = translateLegacyText(node.nodeValue);
              if (translated !== node.nodeValue) node.nodeValue = translated;
            }
            else if (node.nodeType === Node.ELEMENT_NODE) translateTree(node);
          }
        }
      }
    });
    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [locale]);

  return null;
}
